### HOME PAGE
GET http://[::1]:3000/


### GET ALL ITEMS
GET http://[::1]:3000/items


#### GET SINGLE ITEM
GET http://[::1]:3000/items/1


#### ADD AN ITEM
POST http://[::1]:3000/items
Content-Type: application/json

{
    "name": "abc"
}

#### UPDATE A SINGLE ITEM
PUT http://[::1]:3000/items/2
Content-Type: application/json

{
    "name": "test"
}

#### DELETE A SINGLE ITEM
DELETE http://[::1]:3000/items/2





############################ TEST REMOTELY
### GET ALL ITEMS
GET https://test-fastify-tan.vercel.app/items

#### ADD AN ITEM
POST https://test-fastify-tan.vercel.app/items
Content-Type: application/json

{
    "name": "test"
}