### HOME PAGE
GET http://127.0.0.1:5500/

### GET ALL ITEMS
GET http://127.0.0.1:5500/items

#### GET SINGLE ITEM
GET http://127.0.0.1:5500/items/3

#### ADD AN ITEM
POST http://127.0.0.1:5500/items
Content-Type: application/json

{
    "name": "abc"
}

#### DELETE A SINGLE ITEM
DELETE http://127.0.0.1:5500/items/3

#### UPDATE A SINGLE ITEM
PUT http://127.0.0.1:5500/items/1
Content-Type: application/json

{
    "name": "xxx"
}