name = "my-html-worker"
account_id = "d4b54477d7f8617c62464ef485369195"
workers_dev = true
compatibility_date = "2024-04-30"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env]
DB_CONNECTION = "mysql"
DB_HOST = "server3.cretaforce.gr"
DB_PORT = "3306"
DB_DATABASE = "web357_ctcaridkms"
DB_USERNAME = "web357_ctcaridkms"
DB_PASSWORD = "kda99DAJkdaoCA9AJa"